sudo: required
services:
    - docker

before install
    - docker build -t filiparsic/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run filiparsic/react-test npm test -- --coverage

after_success:
    - docker build -t filiparsic/multi-client ./client
    - docker build -t filiparsic/multi-nginx ./nginx
    - docker build -t filiparsic/multi-server ./server
    - docker build -t filiparsic/multi-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

- docker push filiparsic/multi-client
- docker push filiparsic/multi-nginx
- docker push filiparsic/multi-server
- docker push filiparsic/multi-worker
